[package]
name = "bum"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-watch = "8.4.1"
clap = { version = "4.0", features = ["derive"] }
dirs = "5.0.1"
reqwest = "0.12"
tokio = { version = "1", features = ["full"] }
async-std = "1.10"
zip = "1.1"
owo-colors = "4.0"
serde_json = "1.0"
resolve-path = "0.1"
lazy_static = "1.4"

[target.x86_64-unknown-linux-gnu.dependencies]
openssl = { version = "0.10.57", features = ["vendored"] }
[target.x86_64-unknown-linux-musl.dependencies]
openssl = { version = "0.10.57", features = ["vendored"] }
[target.aarch64-unknown-linux-gnu.dependencies]
openssl = { version = "0.10.57", features = ["vendored"] }


[scripts]
watch = "cargo watch -x 'run -- install 1.0.3'"
